<a href="https://colab.research.google.com/github/matheus-feijo/trabalho-IA/blob/main/trabIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Trabalho de IA**


---

## Alunos: Matheus Feijo e Gabriel Arrien




In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.plotting import plot_decision_regions

**PERCEPTRON**

In [ ]:
class Perceptron(object):
	def __init__(self,learning_rate=0.01,epochs=50):
		self.learning_rate = learning_rate
		self.epochs = epochs

	def train(self,X,y):
		self._weights = np.zeros(1 + X.shape[1])
		self._errors = []

		for _ in range(self.epochs):
			errors = 0
			for xi,target in zip(X,y):
				error = (target - self.predict(xi))

				errors += int(error != 0.0)

				update = self.learning_rate + error
				self._weights[1:] += update * xi
				self._weights[0] += update
			self._errors.append(errors)
		return self

	def net_input(self,X):
		w_bias = self._weights[0]
		return np.dot(X,self._weights[1:]) + w_bias
	
	def activation(self,X):
		#print(self.net_input(X))
		return self.net_input(X)

	def predict(self,X):
		#print(np.where(self.activation(X) >= 0.0, 1, -1))
		return np.where(self.activation(X) >= 0.0, 1, -1)


**dados do trabalho**

In [ ]:
#Dados reorganizados
#(maria,nao,sim,nao,nao) SAUDAVEL
#(pedro,nao,nao,sim,nao) SAUDAVEL
#(ana,sim,nao,nao,sim) SAUDAVEL
#(leila,nao,nao,sim,sim) DOENTE
#(joao,sim,sim,nao,sim) DOENTE
#(jose,sim,sim,sim,sim) DOENTE

#OBS: sim == 1 e nao == 0

aux = pd.read_csv("dados.csv")
aux.tail()

y = aux.iloc[0:7,5].values
y = np.where(y=="saudavel",1,-1)
X = aux.iloc[0:7,[1,2,3,4]].values
print(X)
print(y)

[[0 1 0 0]
 [0 0 1 0]
 [1 0 0 1]
 [0 0 1 1]
 [1 1 0 1]
 [1 1 1 1]]
[ 1  1  1 -1 -1 -1]


**chamando o perceptron para treinar os dados**

In [ ]:
clf = Perceptron(epochs=10)
clf.train(X,y)

procentagemAcerto = []

for i in range(0,clf.epochs):
   #aux = quantidade de pessoas testadas - a quantidade de determinações erradas feitas pelo perceptron
   aux =  (100 * clf._errors[i] )/6
   aux = 100 - aux
   aux = round(aux,2)
   #print(aux)

   procentagemAcerto.append(aux) 
  
#Questao 1 
print("Porcentagem de Acerto: ",procentagemAcerto)
#print("Erros: ",clf._errors)
print("pesos calculados depois: ",clf._weights)

Porcentagem de Acerto:  [83.33, 50.0, 33.33, 50.0, 66.67, 66.67, 83.33, 100.0, 100.0, 100.0]
pesos calculados depois:  [ 4.6  2.3 -1.7 -1.7 -5.6]


In [6]:
def treeDecision(person):
  if(person[1] == "sim"):
    if(person[2] == "sim"):
      return "doente"
    else:
      return "saudavel"

  else:
    if(person[2] == "sim"):
      return "saudavel"
    else:
      if(person[3] == "grandes"):
        if(person[4] == "sim"):
          return "doente"
        else:
          return "saudavel"

      else:
        return "Possivelmente Saudavel"
    

In [5]:
luis = ["nao","nao","pequenas","sim"]
laura = ["sim","sim","grandes","sim"]

res1 = treeDecision(luis)
res2 = treeDecision(laura)

print(f"Luis = {res1}\nLaura = {res2}")

Luis = Possivelmente Saudavel
Laura = saudavel
